/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SuperAdmin;

import Manager.AddCancelOrderTab;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Manager.AddaItemTab;
import Manager.OrderCancelSuccessMessage;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;
/**
 *
 * @author G0kul
 */
public class ManageItemsTab extends javax.swing.JFrame {

    /**
     * Creates new form ManageItemsTab
     */
    public ManageItemsTab() {
        initComponents();
    }
    String login;
    public String setId(String id){login = id; return login;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManageItemsTable = new javax.swing.JTable();
        SearchTB = new javax.swing.JTextField();
        SearchBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        AddNewItemBTN = new javax.swing.JButton();
        EditItemBTN = new javax.swing.JButton();
        DeleteItemBTN1 = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("Items Tab");

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Items");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(jLabel1)
                .addContainerGap(496, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ManageItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Item", "Item Size", "Item Weight", "Item Price", "Sender", "Sender Contact", "Sender Address", "Sender Email", "Receiver", "Receiver Contact", "Receiver Address", "Receiver Email", "Order Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ManageItemsTable);

        SearchBTN.setBackground(new java.awt.Color(102, 102, 255));
        SearchBTN.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        SearchBTN.setForeground(new java.awt.Color(255, 255, 255));
        SearchBTN.setText("Search Items");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        BackBTN.setBackground(new java.awt.Color(255, 0, 51));
        BackBTN.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setText("Back");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        AddNewItemBTN.setBackground(new java.awt.Color(0, 0, 204));
        AddNewItemBTN.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        AddNewItemBTN.setForeground(new java.awt.Color(255, 255, 255));
        AddNewItemBTN.setText("Add a new item");
        AddNewItemBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewItemBTNActionPerformed(evt);
            }
        });

        EditItemBTN.setBackground(new java.awt.Color(0, 0, 204));
        EditItemBTN.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        EditItemBTN.setForeground(new java.awt.Color(255, 255, 255));
        EditItemBTN.setText("Edit Item");
        EditItemBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditItemBTNActionPerformed(evt);
            }
        });

        DeleteItemBTN1.setBackground(new java.awt.Color(0, 0, 204));
        DeleteItemBTN1.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        DeleteItemBTN1.setForeground(new java.awt.Color(255, 255, 255));
        DeleteItemBTN1.setText("Delete Item");
        DeleteItemBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemBTN1ActionPerformed(evt);
            }
        });

        Refresh.setBackground(new java.awt.Color(0, 153, 0));
        Refresh.setForeground(new java.awt.Color(255, 255, 255));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("DateFormat(dd-mm-yyyy)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchTB, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBTN))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(AddNewItemBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(DeleteItemBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditItemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBTN)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewItemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditItemBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteItemBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SuperAdminDashboard sa = new SuperAdminDashboard();//set pages
        sa.setId(login);
        sa.setVisible(true);
        
    }//GEN-LAST:event_BackBTNActionPerformed

    private void AddNewItemBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewItemBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddaItemTab fromManager = new AddaItemTab();
        fromManager.setId(login);
        fromManager.setVisible(true);//set pages
    }//GEN-LAST:event_AddNewItemBTNActionPerformed

    private void EditItemBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditItemBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EditItemTab et = new EditItemTab();
        et.setId(login);
        et.setVisible(true);//set pages
    }//GEN-LAST:event_EditItemBTNActionPerformed
    String tableNull = "True";
    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        if(tableNull.equals("True")){
            this.tableNull = "false";
            String filepath = "C:\\\\Users\\\\G0kul\\\\Desktop\\\\oodj\\\\OODJ\\\\src\\\\main\\\\java\\\\Manager\\\\ItemDTL.txt";
            File file = new File(filepath);
            try{
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                DefaultTableModel model = (DefaultTableModel)ManageItemsTable.getModel();
                Object[] lines = br.lines().toArray();
                model.setRowCount(0);
                for(int i = 0; i< lines.length; i++){
                        
                        String[] row = lines[i].toString().split(" ");
                    
                        model.addRow(row);
                    
                }
                fr.close();
                br.close();
            }catch(FileNotFoundException e){} catch (IOException ex) {       
                Logger.getLogger(AddCancelOrderTab.class.getName()).log(Level.SEVERE, null, ex);
            }       
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void DeleteItemBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemBTN1ActionPerformed
        String file = "C:\\Users\\G0kul\\Desktop\\oodj\\OODJ\\src\\main\\java\\Manager\\ItemDTL.txt";
        String tempFile = "C:\\Users\\G0kul\\Desktop\\oodj\\OODJ\\src\\main\\java\\Manager\\tempItem.txt";
        int idPosition = 0;
        int position = ManageItemsTable.getSelectedRow();
        String remove = ManageItemsTable.getValueAt(position, 0).toString();        
       
        
        File oldFile = new File(file);
        File newFile = new File(tempFile);
        String Line;
        String data[];
        try{
            FileWriter fw = new FileWriter(tempFile,true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            
            System.out.println(position);
            System.out.println(remove);
            while((Line = br.readLine()) != null){
                data = Line.split(" ");
                if(!(data[idPosition].equalsIgnoreCase(remove))){
                    pw.println(Line);
                }
            }
            pw.flush();
            pw.close();
            fr.close();
            br.close();
            bw.close();
            fw.close();
            
            oldFile.delete();
            File newname = new File(file);
            newFile.renameTo(newname);
            
            this.dispose();
            OrderCancelSuccessMessage oc = new OrderCancelSuccessMessage();
            oc.setId(login);
            oc.setVisible(true);
        }catch(IOException e){System.out.println(e);}
    }//GEN-LAST:event_DeleteItemBTN1ActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        tableNull = "True";
        String filepath = "C:\\Users\\G0kul\\Desktop\\oodj\\OODJ\\src\\main\\java\\Manager\\ItemDTL.txt";
            File file = new File(filepath);
            try{
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                
                String Search = SearchTB.getText();
                
                DefaultTableModel model = (DefaultTableModel)ManageItemsTable.getModel();
                Object[] lines = br.lines().toArray();
                model.setRowCount(0);
                for(int i = 0; i< lines.length; i++){
                    
                    String[] row = lines[i].toString().split(" ");
                    
                    //search on the basis of item id
                    if(row[0].equals(Search)){
                        model.setRowCount(0);
                        model.addRow(row);
                    }
                                      
                    //Search on the basis of receiver, sender, address, item name
                    if(row[1].equals(Search) || row[9].equals(Search) || row[7].equals(Search) || row[11].equals(Search)|| row[5].equals(Search)|| row[13].equals(Search) ){
                        
                        model.addRow(row);
                    }
                    
                    
                }
            }catch(FileNotFoundException e){}  
    }//GEN-LAST:event_SearchBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageItemsTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageItemsTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageItemsTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageItemsTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageItemsTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewItemBTN;
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton DeleteItemBTN1;
    private javax.swing.JButton EditItemBTN;
    private javax.swing.JTable ManageItemsTable;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JTextField SearchTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
