
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SuperAdmin;
import Login.Panel.LoginTab;

/**
 *
 * @author G0kul x Arun
 */
public class SuperAdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ManagerDashboard
     */
    public SuperAdminDashboard() {
        initComponents();
    }
    String login;
    public String setId(String id){login = id; return login;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ManageItems = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        ManageReports = new javax.swing.JButton();
        ManageFeedback = new javax.swing.JButton();
        ManageManager = new javax.swing.JButton();
        ManageDeliveryStaff = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Dashboard");

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Super Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(282, 282, 282))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        ManageItems.setBackground(new java.awt.Color(0, 0, 255));
        ManageItems.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        ManageItems.setForeground(new java.awt.Color(255, 255, 255));
        ManageItems.setText("Manage Items");
        ManageItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageItemsActionPerformed(evt);
            }
        });

        LogOut.setBackground(new java.awt.Color(255, 0, 0));
        LogOut.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setText("Log out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        ManageReports.setBackground(new java.awt.Color(0, 0, 255));
        ManageReports.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        ManageReports.setForeground(new java.awt.Color(255, 255, 255));
        ManageReports.setText("View Reports");
        ManageReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageReportsActionPerformed(evt);
            }
        });

        ManageFeedback.setBackground(new java.awt.Color(0, 0, 255));
        ManageFeedback.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        ManageFeedback.setForeground(new java.awt.Color(255, 255, 255));
        ManageFeedback.setText("View Feedbacks");
        ManageFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageFeedbackActionPerformed(evt);
            }
        });

        ManageManager.setBackground(new java.awt.Color(0, 0, 255));
        ManageManager.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        ManageManager.setForeground(new java.awt.Color(255, 255, 255));
        ManageManager.setText("Manage Manager Account");
        ManageManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageManagerActionPerformed(evt);
            }
        });

        ManageDeliveryStaff.setBackground(new java.awt.Color(0, 0, 255));
        ManageDeliveryStaff.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        ManageDeliveryStaff.setForeground(new java.awt.Color(255, 255, 255));
        ManageDeliveryStaff.setText("Manage Delivery Staff ");
        ManageDeliveryStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDeliveryStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ManageFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageDeliveryStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageItems, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageManager, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageReports, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageItems, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageManager, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageDeliveryStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageReports, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginTab().setVisible(true);//set pages
    }//GEN-LAST:event_LogOutActionPerformed

    private void ManageDeliveryStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDeliveryStaffActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ManageDeliveryStaffTab md = new ManageDeliveryStaffTab();
        md.setId(login);
        md.setVisible(true);//set pages
    }//GEN-LAST:event_ManageDeliveryStaffActionPerformed

    private void ManageItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageItemsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ManageItemsTab mt = new ManageItemsTab();
        mt.setId(login);
        mt.setVisible(true);
    }//GEN-LAST:event_ManageItemsActionPerformed

    private void ManageFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageFeedbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FeedbackTab ft = new FeedbackTab();
        ft.setId(login);
        ft.setVisible(true);//set pages
    }//GEN-LAST:event_ManageFeedbackActionPerformed

    private void ManageManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageManagerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ManageManagerAccountView mg = new ManageManagerAccountView();
        mg.setId(login);
        mg.setVisible(true);
        
    }//GEN-LAST:event_ManageManagerActionPerformed

    private void ManageReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageReportsActionPerformed
       this.dispose();
        ReportViewTab rv = new ReportViewTab();
        rv.setId(login);
        rv.setVisible(true);
    }//GEN-LAST:event_ManageReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperAdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut;
    private javax.swing.JButton ManageDeliveryStaff;
    private javax.swing.JButton ManageFeedback;
    private javax.swing.JButton ManageItems;
    private javax.swing.JButton ManageManager;
    private javax.swing.JButton ManageReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
