/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DeliveryPerson;

import Login.Panel.LoginTab;

/**
 *
 * @author G0kul x Arun
 */
public class DeliveryStaffDashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryStaffDashboardView
     */
    public DeliveryStaffDashboardView() {
        initComponents();
    }
    String login;
    public String setId(String id){login = id; return login;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PersonalProfileBTN = new javax.swing.JButton();
        DeliveriesBTN = new javax.swing.JButton();
        DeliveryLogBTN = new javax.swing.JButton();
        OTPconfirmationBTN = new javax.swing.JButton();
        LogOutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delivery Staff Dashboard");

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delivery Staff ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        PersonalProfileBTN.setBackground(new java.awt.Color(0, 0, 204));
        PersonalProfileBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        PersonalProfileBTN.setForeground(new java.awt.Color(255, 255, 255));
        PersonalProfileBTN.setText("View Profile");
        PersonalProfileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalProfileBTNActionPerformed(evt);
            }
        });

        DeliveriesBTN.setBackground(new java.awt.Color(0, 0, 204));
        DeliveriesBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        DeliveriesBTN.setForeground(new java.awt.Color(255, 255, 255));
        DeliveriesBTN.setText("Deliveries");
        DeliveriesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveriesBTNActionPerformed(evt);
            }
        });

        DeliveryLogBTN.setBackground(new java.awt.Color(0, 0, 204));
        DeliveryLogBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        DeliveryLogBTN.setForeground(new java.awt.Color(255, 255, 255));
        DeliveryLogBTN.setText("Delivery Log");
        DeliveryLogBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryLogBTNActionPerformed(evt);
            }
        });

        OTPconfirmationBTN.setBackground(new java.awt.Color(0, 0, 204));
        OTPconfirmationBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        OTPconfirmationBTN.setForeground(new java.awt.Color(255, 255, 255));
        OTPconfirmationBTN.setText("OTP Confirmation");
        OTPconfirmationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTPconfirmationBTNActionPerformed(evt);
            }
        });

        LogOutBTN.setBackground(new java.awt.Color(255, 0, 0));
        LogOutBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        LogOutBTN.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBTN.setText("Log Out");
        LogOutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PersonalProfileBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeliveriesBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeliveryLogBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OTPconfirmationBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(LogOutBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(PersonalProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeliveriesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeliveryLogBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OTPconfirmationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(LogOutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginTab().setVisible(true);//set pages
    }//GEN-LAST:event_LogOutBTNActionPerformed

    private void OTPconfirmationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTPconfirmationBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        OtpConfirmationTab oc = new OtpConfirmationTab();
        oc.setId(login);
        oc.setVisible(true);//set pages
    }//GEN-LAST:event_OTPconfirmationBTNActionPerformed

    private void PersonalProfileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalProfileBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewOwnProfile vp = new ViewOwnProfile();
        vp.setId(login);
        vp.setVisible(true);//set pages
    }//GEN-LAST:event_PersonalProfileBTNActionPerformed

    private void DeliveryLogBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryLogBTNActionPerformed
        this.dispose();
        DeliveryLogs dl = new DeliveryLogs();
        dl.setId(login);
        dl.setVisible(true);
    }//GEN-LAST:event_DeliveryLogBTNActionPerformed

    private void DeliveriesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveriesBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Deliveries d = new Deliveries();
        d.setId(login);
        d.setVisible(true);
    }//GEN-LAST:event_DeliveriesBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaffDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaffDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaffDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaffDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryStaffDashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeliveriesBTN;
    private javax.swing.JButton DeliveryLogBTN;
    private javax.swing.JButton LogOutBTN;
    private javax.swing.JButton OTPconfirmationBTN;
    private javax.swing.JButton PersonalProfileBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
