/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DeliveryPerson;

import Manager.ViewProfileTab;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author G0kul x Arun
 */
public class OtpConfirmationTab extends javax.swing.JFrame {

    /**
     * Creates new form OtpConfirmationTab
     */
    public OtpConfirmationTab() {
        initComponents();
    }
    String login;
    public String setId(String id){login = id; return login;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ItemID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        OTPTB = new javax.swing.JTextField();
        SubmitBTN = new javax.swing.JButton();
        SubmitBTN1 = new javax.swing.JButton();
        Notification = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OTP Confirmation Process");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        jLabel2.setText("Enter Product ID:");

        jLabel3.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        jLabel3.setText("Enter OTP Code:");

        SubmitBTN.setBackground(new java.awt.Color(0, 204, 0));
        SubmitBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        SubmitBTN.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBTN.setText("Submit");
        SubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTNActionPerformed(evt);
            }
        });

        SubmitBTN1.setBackground(new java.awt.Color(204, 0, 0));
        SubmitBTN1.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        SubmitBTN1.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBTN1.setText("Back");
        SubmitBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTN1ActionPerformed(evt);
            }
        });

        Notification.setText("Notification Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemID, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(OTPTB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(SubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(SubmitBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Notification, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Notification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(OTPTB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(SubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTN1ActionPerformed
        this.dispose();
        DeliveryStaffDashboardView dv = new DeliveryStaffDashboardView();
        dv.setId(login);
        dv.setVisible(true);
    }//GEN-LAST:event_SubmitBTN1ActionPerformed

    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed
        try{
            
            String line,ID,OTP ;
            LocalDateTime dt = LocalDateTime.now();
            DateTimeFormatter df = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String TodayDate = dt.format(df);
            File f = new File("C:\\Users\\G0kul\\Desktop\\oodj\\OODJ\\src\\main\\java\\Manager\\assignedOrder.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            
            String SearchID = this.ItemID.getText();
            String OTPP = this.OTPTB.getText();
            while((line = br.readLine()) != null){
                ID = line.split(" ")[0];
                OTP = line.split(" ")[20];
                
                if(ID.equals(SearchID)){
                    if(OTP.equals(OTPP)){
                        ArrayList <String> Temp = new ArrayList <>();
                        try{
                            try(FileReader frr = new FileReader("C:\\Users\\G0kul\\Desktop\\oodj\\OODJ\\src\\main\\java\\Manager\\assignedOrder.txt")){
                                Scanner r = new Scanner(frr);
                                String Line;
                                String [] LineArray;
                                while((Line = r.nextLine())!=null){
                                    LineArray = Line.split(" ");
                                    if(LineArray[0].equals(ID)){
                                        Temp.add(LineArray[0]+" "+LineArray[1]+" "+LineArray[2]+" "+LineArray[3]+" "+LineArray[4]+" "+LineArray[5]+" "+LineArray[6]+" "+LineArray[7]+" "+LineArray[8]+" "+LineArray[9]+" "+LineArray[10]+" "+LineArray[11]+" "+LineArray[12]+" "+LineArray[13]+" "+LineArray[14]+" "+LineArray[15]+" "+LineArray[16]+" "+LineArray[17]+" "+LineArray[18]+" "+LineArray[19]+" "+LineArray[20]+" "+"Delivered"+" "+LineArray[22]+" "+TodayDate);
                                    }else{
                                        Temp.add(Line);
                                    }
                                }
                                frr.close();
                            }catch(Exception e){            
                            }
                        }catch(Exception e){
                        }

                        try{
                            try(PrintWriter pr = new PrintWriter("C:\\Users\\G0kul\\Desktop\\oodj\\OODJ\\src\\main\\java\\Manager\\assignedOrder.txt")){
                                for(String Str:Temp){
                                    pr.println(Str);
                                }
                                pr.close();
                            }catch(Exception e){
                            }
                        }catch(Exception e){}
                        
                        this.Notification.setText("Product Delivered Successfully");
                    }
                    if(!(OTP.equals(OTPP))){
                        this.Notification.setText("Product ID and OTP Mis-Matched");
                    }
                }
                /*if(!(ID.equals(SearchID))){
                    this.Notification.setText("Invalid Id");
                } */                  
            }
        fr.close();
        br.close();
        }catch(IOException ex){
            Logger.getLogger(ViewProfileTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtpConfirmationTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtpConfirmationTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtpConfirmationTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtpConfirmationTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtpConfirmationTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ItemID;
    private javax.swing.JTextField Notification;
    private javax.swing.JTextField OTPTB;
    private javax.swing.JButton SubmitBTN;
    private javax.swing.JButton SubmitBTN1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
