/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author G0kul x Arun
 */
public class AddCancelOrderTab extends javax.swing.JFrame {

    /**
     * Creates new form AddCancelOrderTab
     */
    String login;
    public String setId(String id){login = id; return login;}
    public AddCancelOrderTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderListTable = new javax.swing.JTable();
        BackBTN1 = new javax.swing.JButton();
        BackBTN2 = new javax.swing.JButton();
        BackBTN3 = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Cancel Order Tab");

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add / Cancel Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        BackBTN.setBackground(new java.awt.Color(255, 0, 0));
        BackBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setText("Back");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        OrderListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item", "Item Size", "Item Weight", "Item Price", "sender", "Sender Contact", "Sender Address", "Sender Email", "Receiver", "Receiver Contact", "Receiver Address", "Receiver Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrderListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OrderListTable);

        BackBTN1.setBackground(new java.awt.Color(0, 0, 255));
        BackBTN1.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        BackBTN1.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN1.setText("Add Order");
        BackBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTN1ActionPerformed(evt);
            }
        });

        BackBTN2.setBackground(new java.awt.Color(0, 0, 255));
        BackBTN2.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        BackBTN2.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN2.setText("Cancel Order");
        BackBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTN2ActionPerformed(evt);
            }
        });

        BackBTN3.setBackground(new java.awt.Color(0, 0, 255));
        BackBTN3.setFont(new java.awt.Font("Poppins", 3, 12)); // NOI18N
        BackBTN3.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN3.setText("Edit Order");
        BackBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTN3ActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(0, 255, 0));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackBTN)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BackBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BackBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BackBTN3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackBTN)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        this.dispose();
        ManagerDashboardTab manager = new ManagerDashboardTab();
        manager.setId(login);
        manager.setVisible(true);//set pages
    }//GEN-LAST:event_BackBTNActionPerformed

    private void BackBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTN1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddaItemTab add = new AddaItemTab();
        add.setId(login);
        add.setVisible(true);//set pages
    }//GEN-LAST:event_BackBTN1ActionPerformed

    private void BackBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTN3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EditItemTab edit = new EditItemTab();
        edit.setId(login);
        edit.setVisible(true);//set pages
    }//GEN-LAST:event_BackBTN3ActionPerformed

    String tableNull = "True";
    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        
        if(tableNull.equals("True")){
            this.tableNull = "false";
            String filepath = "C:\\\\Users\\\\G0kul\\\\Desktop\\\\oodj\\\\OODJ\\\\src\\\\main\\\\java\\\\Manager\\\\ItemDTL.txt";
            File file = new File(filepath);
            try{
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                DefaultTableModel model = (DefaultTableModel)OrderListTable.getModel();
                
                Object[] lines = br.lines().toArray();
                for(int i = 0; i< lines.length; i++){
                    
                        String[] row = lines[i].toString().split(" ");
                    
                        model.addRow(row);
                    
                }
                fr.close();
                br.close();
            }catch(FileNotFoundException e){} catch (IOException ex) {       
                Logger.getLogger(AddCancelOrderTab.class.getName()).log(Level.SEVERE, null, ex);
            }       
        }
    }//GEN-LAST:event_refreshActionPerformed

    private void BackBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTN2ActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel tb = (DefaultTableModel)OrderListTable.getModel();
        //if(OrderListTable.getRowCount()==1){
          //  tb.removeRow(OrderListTable.getSelectedRow());
        //}
        
        //bigro
        
        String file = "C:\\Users\\G0kul\\Desktop\\oodj\\OODJ\\src\\main\\java\\Manager\\ItemDTL.txt";
        String tempFile = "C:\\Users\\G0kul\\Desktop\\oodj\\OODJ\\src\\main\\java\\Manager\\tempItem.txt";
        int idPosition = 0;
        int position = OrderListTable.getSelectedRow();
        String remove = OrderListTable.getValueAt(position, 0).toString();        
       
        
        File oldFile = new File(file);
        File newFile = new File(tempFile);
        String Line;
        String data[];
        try{
            FileWriter fw = new FileWriter(tempFile,true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            
            System.out.println(position);
            System.out.println(remove);
            while((Line = br.readLine()) != null){
                data = Line.split(" ");
                if(!(data[idPosition].equalsIgnoreCase(remove))){
                    pw.println(Line);
                }
            }
            pw.flush();
            pw.close();
            fr.close();
            br.close();
            bw.close();
            fw.close();
            
            oldFile.delete();
            File newname = new File(file);
            newFile.renameTo(newname);
            
            this.dispose();
            OrderCancelSuccessMessage oc = new OrderCancelSuccessMessage();
            oc.setId(login);
            oc.setVisible(true);
        }catch(IOException e){System.out.println(e);}
    }//GEN-LAST:event_BackBTN2ActionPerformed

    private void OrderListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderListTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderListTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCancelOrderTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCancelOrderTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCancelOrderTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCancelOrderTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCancelOrderTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton BackBTN1;
    private javax.swing.JButton BackBTN2;
    private javax.swing.JButton BackBTN3;
    private javax.swing.JTable OrderListTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
