/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import Login.Panel.LoginTab;
import Login.Panel.TrackAndPrint;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author G0kul x Arun
 */
public class ManagerDashboardTab extends javax.swing.JFrame {

    

    /**
     * Creates new form ManagerDashboardTab
     * @param id
     */
    String login;
    public ManagerDashboardTab() {
        initComponents();
    }
    public String setId(String id){login = id; return login;}
    
    
    

    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ViewProfileBTN = new javax.swing.JButton();
        AddOrCancelBTN = new javax.swing.JButton();
        DeliveryBTN = new javax.swing.JButton();
        AssignOrderBTN = new javax.swing.JButton();
        TrackOrderBTN = new javax.swing.JButton();
        LogOutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manager ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        ViewProfileBTN.setBackground(new java.awt.Color(0, 0, 255));
        ViewProfileBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        ViewProfileBTN.setForeground(new java.awt.Color(255, 255, 255));
        ViewProfileBTN.setText("View Profile");
        ViewProfileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileBTNActionPerformed(evt);
            }
        });

        AddOrCancelBTN.setBackground(new java.awt.Color(0, 0, 255));
        AddOrCancelBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        AddOrCancelBTN.setForeground(new java.awt.Color(255, 255, 255));
        AddOrCancelBTN.setText("Add / Cancel Order");
        AddOrCancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOrCancelBTNActionPerformed(evt);
            }
        });

        DeliveryBTN.setBackground(new java.awt.Color(0, 0, 255));
        DeliveryBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        DeliveryBTN.setForeground(new java.awt.Color(255, 255, 255));
        DeliveryBTN.setText("View Delivery Staff");
        DeliveryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryBTNActionPerformed(evt);
            }
        });

        AssignOrderBTN.setBackground(new java.awt.Color(0, 0, 255));
        AssignOrderBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        AssignOrderBTN.setForeground(new java.awt.Color(255, 255, 255));
        AssignOrderBTN.setText("Assign Order");
        AssignOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignOrderBTNActionPerformed(evt);
            }
        });

        TrackOrderBTN.setBackground(new java.awt.Color(0, 0, 255));
        TrackOrderBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        TrackOrderBTN.setForeground(new java.awt.Color(255, 255, 255));
        TrackOrderBTN.setText("Track Order");
        TrackOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrackOrderBTNActionPerformed(evt);
            }
        });

        LogOutBTN.setBackground(new java.awt.Color(255, 0, 0));
        LogOutBTN.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        LogOutBTN.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBTN.setText("Log Out");
        LogOutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewProfileBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddOrCancelBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeliveryBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AssignOrderBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrackOrderBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogOutBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(ViewProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddOrCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeliveryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AssignOrderBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TrackOrderBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogOutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeliveryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewDeliveryStaff vd = new ViewDeliveryStaff();
        vd.setId(login);
        vd.setVisible(true);//set pages
    }//GEN-LAST:event_DeliveryBTNActionPerformed

    private void LogOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginTab().setVisible(true);//set pages
    }//GEN-LAST:event_LogOutBTNActionPerformed

    private void AddOrCancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOrCancelBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddCancelOrderTab addcancel = new AddCancelOrderTab();
        addcancel.setId(login);
        addcancel.setVisible(true);//set pages
    }//GEN-LAST:event_AddOrCancelBTNActionPerformed

    private void ViewProfileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileBTNActionPerformed
        try {
            // TODO add your handling code here:
            this.dispose();
            ViewProfileTab ViewProfileTab = new ViewProfileTab();
            ViewProfileTab.setId(login);
            ViewProfileTab.setVisible(true);//set pages
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManagerDashboardTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ViewProfileBTNActionPerformed

    private void AssignOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignOrderBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AssignOrderTab assaign = new AssignOrderTab();
        assaign.setId(login);
        assaign.setVisible(true);//set pages
    }//GEN-LAST:event_AssignOrderBTNActionPerformed

    private void TrackOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrackOrderBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TrackAndPrint tp = new TrackAndPrint();
        tp.setId(login);
        tp.setVisible(true);
        
    }//GEN-LAST:event_TrackOrderBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(String Id) {
                new ManagerDashboardTab().setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrCancelBTN;
    private javax.swing.JButton AssignOrderBTN;
    private javax.swing.JButton DeliveryBTN;
    private javax.swing.JButton LogOutBTN;
    private javax.swing.JButton TrackOrderBTN;
    private javax.swing.JButton ViewProfileBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
